stages:
  - build

.template-build:
  stage: build
  image:
    name: moby/buildkit:rootless
    entrypoint: [""]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox 
    BUILDKIT_EXTRA_OPTS: ""
    TARGET_DOCKER_FILE: Dockerfile
  before_script:
    - mkdir -p /tmp/buildkit-certs
    - echo "$CA_CERT" > /tmp/buildkit-certs/ca.crt
  script:
    - test -n "${BUILD_CONTEXT_DIR}" || (echo "BUILD_CONTEXT_DIR is not set" && exit 1)
    - test -n "${TARGET_DOCKER_FILE}" || (echo "TARGET_DOCKER_FILE is not set" && exit 1)
    - export REGISTRY_CLEAN=$(echo -n "$DEV_REGISTRY" | tr -d '\n')
    - export TARGET_NAME_CLEAN=$(echo -n "$TARGET_IMAGE_NAME" | tr -d '\n')
    - export CLEAN_TAG=$(echo -n "$TARGET_IMAGE_TAG" | tr -d '\n')
    - |
      if [ -z "$REGISTRY_CLEAN" ]; then
        export IMAGE_NAME="${TARGET_NAME_CLEAN}:${CLEAN_TAG}"
        export CACHE_IMAGE="${TARGET_NAME_CLEAN}:cache"
      else
        export IMAGE_NAME="${REGISTRY_CLEAN}/${TARGET_NAME_CLEAN}:${CLEAN_TAG}"
        export CACHE_IMAGE="${REGISTRY_CLEAN}/${TARGET_NAME_CLEAN}:cache"
      fi
    - echo "Building ${BUILD_CONTEXT_DIR}/${TARGET_DOCKER_FILE} → $IMAGE_NAME"
    - |
      buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context="${CI_PROJECT_DIR}/${BUILD_CONTEXT_DIR}" \
        --local dockerfile="${CI_PROJECT_DIR}/${BUILD_CONTEXT_DIR}" \
        --opt filename="${TARGET_DOCKER_FILE}" \
        --registry-auth-tlscontext host=https://13.250.126.255:5000,ca=/tmp/certs/ca.crt \
        --export-cache type=registry,ref=$CACHE_IMAGE \
        --import-cache type=registry,ref=$CACHE_IMAGE \
        --opt platform=linux/amd64 \
        ${BUILDKIT_EXTRA_OPTS} \
        --output type=image,name=$IMAGE_NAME,push=true
  tags:
  - ec2-runner


build:backend:
  extends: .template-build
  variables:
    BUILD_CONTEXT_DIR: backend
    TARGET_IMAGE_NAME: "sar-mel/frontend"
    TARGET_IMAGE_TAG: "${CI_COMMIT_REF_SLUG}"
  only:
    refs:
      - main


build:frontend:
  extends: .template-build
  variables:
    BUILD_CONTEXT_DIR: frontend
    TARGET_IMAGE_NAME: "sar-mel/frontend"
    TARGET_IMAGE_TAG: "${CI_COMMIT_REF_SLUG}"
  only:
    refs:
      - main
