"""add image_url to menu_items

Revision ID: 9a6c3c9aceb0
Revises: 1c590214ae3d
Create Date: 2026-05-29 01:46:06.696471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6c3c9aceb0'
down_revision: Union[str, Sequence[str], None] = '1c590214ae3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'image_url')
    # ### end Alembic commands ###
